name: Publish Terraform GHA image to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    # permissions: write-all
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64/v8,linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dind image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dind.Dockerfile
          platforms: linux/arm64/v8,linux/amd64,linux/arm64 # used this to work on a specific platform
          push: true
          tags: ghcr.io/adefemi171/terraform-gha-dind:latest
      
      - name: Build and push ARC image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./arc.Dockerfile
          platforms: linux/arm64/v8,linux/amd64,linux/arm64 # used this to work on a specific platform
          push: true
          tags: ghcr.io/adefemi171/terraform-gha-arc:latest
      
